/**
 * 회사소개서 & 포트폴리오 관리 — 기업별 소개서/포트폴리오 목록
 * /portfolio 화면(사용자용)과 동일한 데이터를 관리자가 전체 기업 단위로 조회
 */
import { useState } from "react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Eye, Search, ChevronDown, ChevronRight, ExternalLink } from "lucide-react"
import { Link } from "wouter"
import { cn } from "@/lib/utils"

type CompanyType = "광고주" | "대행사" | "제작사"

interface PortfolioEntry {
  id: string
  title: string
  visible: boolean
  createdAt: string
  isAutoGenerated?: boolean
}

interface CompanyRow {
  id: string
  companyName: string
  companyType: CompanyType
  description: string
  recentClients: string[]
  tags: string[]
  activityCount: number
  portfolios: PortfolioEntry[]
  lastUpdated: string
}

const MOCK_COMPANIES: CompanyRow[] = [
  {
    id: "company-001",
    companyName: "솜사탕애드",
    companyType: "대행사",
    description: "Creative중심 대행사",
    recentClients: ["빙그레", "초록우산 어린이재단", "동원식품", "해양수산부"],
    tags: ["전기전자", "기업PR", "식품/제과", "공사/단체/공익/기업PR", "#공공기관_정책캠페인", "#뷰티_숏폼"],
    activityCount: 3,
    lastUpdated: "2025-07-03",
    portfolios: [
      { id: "p-001-1", title: "기본소개서 (자동생성됨)", visible: true, createdAt: "2025-05-01", isAutoGenerated: true },
      { id: "p-001-2", title: "Campaign creators 솜사탕애드 입", visible: true, createdAt: "2025-07-03" },
    ],
  },
  {
    id: "company-002",
    companyName: "스튜디오 블루",
    companyType: "제작사",
    description: "영상 전문 제작사",
    recentClients: ["삼성전자", "LG화학", "현대자동차"],
    tags: ["영상", "CF", "#급행제작 대응", "#뷰티_숏폼"],
    activityCount: 7,
    lastUpdated: "2026-02-15",
    portfolios: [
      { id: "p-002-1", title: "기본소개서 (자동생성됨)", visible: true, createdAt: "2024-11-10", isAutoGenerated: true },
      { id: "p-002-2", title: "2025 영상 포트폴리오", visible: true, createdAt: "2025-03-22" },
      { id: "p-002-3", title: "뷰티 전문 소개서", visible: false, createdAt: "2026-01-05" },
    ],
  },
  {
    id: "company-003",
    companyName: "크리에이티브 랩",
    companyType: "대행사",
    description: "디지털 마케팅 전문",
    recentClients: ["카카오", "네이버", "쿠팡"],
    tags: ["디지털", "SNS마케팅", "#퍼포먼스마케팅"],
    activityCount: 12,
    lastUpdated: "2026-03-10",
    portfolios: [
      { id: "p-003-1", title: "기본소개서 (자동생성됨)", visible: true, createdAt: "2025-01-15", isAutoGenerated: true },
    ],
  },
  {
    id: "company-004",
    companyName: "글로벌 마케팅",
    companyType: "광고주",
    description: "글로벌 소비재 브랜드",
    recentClients: [],
    tags: ["FMCG", "글로벌"],
    activityCount: 0,
    lastUpdated: "2025-12-01",
    portfolios: [
      { id: "p-004-1", title: "기본소개서 (자동생성됨)", visible: false, createdAt: "2025-12-01", isAutoGenerated: true },
    ],
  },
  {
    id: "company-005",
    companyName: "픽셀스튜디오",
    companyType: "제작사",
    description: "모션그래픽·2D/3D 전문",
    recentClients: ["넷마블", "엔씨소프트", "카카오게임즈", "넥슨"],
    tags: ["모션그래픽", "2D", "3D", "게임광고", "#게임_전문"],
    activityCount: 5,
    lastUpdated: "2026-03-20",
    portfolios: [
      { id: "p-005-1", title: "기본소개서 (자동생성됨)", visible: true, createdAt: "2025-04-18", isAutoGenerated: true },
      { id: "p-005-2", title: "게임광고 전문 소개서", visible: true, createdAt: "2025-09-30" },
      { id: "p-005-3", title: "2026 모션그래픽 포트폴리오", visible: true, createdAt: "2026-02-14" },
    ],
  },
  {
    id: "company-006",
    companyName: "애드마스터",
    companyType: "대행사",
    description: "TV·OTT 광고 종합 대행",
    recentClients: ["롯데", "신세계", "GS리테일"],
    tags: ["TV광고", "OTT", "종합광고"],
    activityCount: 2,
    lastUpdated: "2026-01-28",
    portfolios: [
      { id: "p-006-1", title: "기본소개서 (자동생성됨)", visible: true, createdAt: "2025-06-10", isAutoGenerated: true },
      { id: "p-006-2", title: "TV광고 전문 소개서", visible: false, createdAt: "2025-11-20" },
    ],
  },
]

function CompanyTypeBadge({ type }: { type: CompanyType }) {
  const map: Record<CompanyType, string> = {
    광고주: "border-pink-300 text-pink-600 bg-pink-50",
    대행사: "border-orange-300 text-orange-600 bg-orange-50",
    제작사: "border-teal-300 text-teal-600 bg-teal-50",
  }
  return (
    <Badge variant="outline" className={cn("text-xs font-normal", map[type])}>
      {type}
    </Badge>
  )
}

function VisibleBadge({ visible }: { visible: boolean }) {
  return (
    <span
      className={cn(
        "inline-block px-2 py-0.5 rounded text-xs font-normal",
        visible ? "bg-green-100 text-green-700" : "bg-gray-100 text-gray-500"
      )}
    >
      {visible ? "공개" : "비공개"}
    </span>
  )
}

export default function CompanyPortfoliosPage() {
  const [search, setSearch] = useState("")
  const [typeFilter, setTypeFilter] = useState("전체")
  const [expandedId, setExpandedId] = useState<string | null>(null)

  const filtered = MOCK_COMPANIES.filter((c) => {
    const matchesSearch =
      c.companyName.includes(search) ||
      c.description.includes(search) ||
      c.tags.some((t) => t.includes(search))
    const matchesType = typeFilter === "전체" || c.companyType === typeFilter
    return matchesSearch && matchesType
  })

  const summary = [
    { label: "전체 기업", value: MOCK_COMPANIES.length, color: "text-gray-800" },
    {
      label: "소개서 총 건수",
      value: MOCK_COMPANIES.reduce((sum, c) => sum + c.portfolios.length, 0),
      color: "text-blue-600",
    },
    {
      label: "공개 소개서",
      value: MOCK_COMPANIES.reduce(
        (sum, c) => sum + c.portfolios.filter((p) => p.visible).length,
        0
      ),
      color: "text-emerald-600",
    },
    {
      label: "비공개 소개서",
      value: MOCK_COMPANIES.reduce(
        (sum, c) => sum + c.portfolios.filter((p) => !p.visible).length,
        0
      ),
      color: "text-gray-400",
    },
  ]

  return (
    <div className="space-y-6 p-6">
      {/* 헤더 */}
      <div>
        <h1 className="text-2xl font-bold text-foreground">회사소개서 &amp; 포트폴리오</h1>
        <p className="text-muted-foreground">기업별 등록된 소개서·포트폴리오 현황을 조회합니다</p>
      </div>

      {/* 요약 카드 */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {summary.map((s) => (
          <div
            key={s.label}
            className="bg-white rounded-xl border border-gray-100 shadow-sm p-4 text-center"
          >
            <div className={cn("text-2xl font-bold", s.color)}>{s.value}</div>
            <div className="text-xs text-gray-500 mt-0.5">{s.label}</div>
          </div>
        ))}
      </div>

      {/* 필터 */}
      <div className="flex flex-wrap items-center gap-2">
        <div className="relative flex-1 min-w-[200px]">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="기업명, 설명, 태그 검색..."
            className="pl-9"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <Select value={typeFilter} onValueChange={setTypeFilter}>
          <SelectTrigger className="w-32">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="전체">전체 유형</SelectItem>
            <SelectItem value="광고주">광고주</SelectItem>
            <SelectItem value="대행사">대행사</SelectItem>
            <SelectItem value="제작사">제작사</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* 기업별 목록 */}
      <div className="space-y-3">
        {filtered.length === 0 ? (
          <div className="bg-white rounded-xl border border-gray-100 shadow-sm py-12 text-center text-gray-400 text-sm">
            검색 결과가 없습니다
          </div>
        ) : (
          filtered.map((company) => {
            const isOpen = expandedId === company.id
            const publicCount = company.portfolios.filter((p) => p.visible).length
            return (
              <div
                key={company.id}
                className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden"
              >
                {/* 기업 행 — 클릭 시 소개서 목록 펼치기 */}
                <div
                  className="flex items-start gap-4 p-4 cursor-pointer hover:bg-gray-50/60 transition-colors"
                  onClick={() => setExpandedId(isOpen ? null : company.id)}
                >
                  <div className="mt-0.5 text-gray-400">
                    {isOpen ? (
                      <ChevronDown className="h-4 w-4" />
                    ) : (
                      <ChevronRight className="h-4 w-4" />
                    )}
                  </div>

                  {/* 기업 정보 */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap mb-1">
                      <span className="font-semibold text-gray-900">{company.companyName}</span>
                      <CompanyTypeBadge type={company.companyType} />
                      <span className="text-sm text-gray-500">{company.description}</span>
                    </div>

                    {/* 대표 광고주 */}
                    {company.recentClients.length > 0 && (
                      <div className="flex flex-wrap gap-1.5 mb-1.5">
                        {company.recentClients.slice(0, 4).map((c) => (
                          <span key={c} className="text-xs text-gray-500 bg-gray-50 border border-gray-100 rounded px-1.5 py-0.5">
                            {c}
                          </span>
                        ))}
                      </div>
                    )}

                    {/* 태그 */}
                    <div className="flex flex-wrap gap-1">
                      {company.tags.slice(0, 5).map((t) => (
                        <span key={t} className="text-xs text-gray-500 bg-gray-50 rounded-full px-2 py-0.5">
                          {t}
                        </span>
                      ))}
                      {company.tags.length > 5 && (
                        <span className="text-xs text-gray-400">+{company.tags.length - 5} more</span>
                      )}
                    </div>
                  </div>

                  {/* 우측 통계 */}
                  <div className="shrink-0 text-right text-xs text-gray-500 space-y-0.5">
                    <div>
                      소개서{" "}
                      <span className="font-medium text-gray-800">{company.portfolios.length}건</span>
                      {" "}(공개 {publicCount})
                    </div>
                    <div>Cotton Candy 활동 {company.activityCount}작품</div>
                    <div>최종 수정 {company.lastUpdated}</div>
                    <div className="pt-1" onClick={(e) => e.stopPropagation()}>
                      <Link href={`/admin/companies/${company.id}`}>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-6 px-2 text-xs text-gray-400 hover:text-gray-700"
                        >
                          <ExternalLink className="h-3 w-3 mr-1" />
                          기업 상세
                        </Button>
                      </Link>
                    </div>
                  </div>
                </div>

                {/* 소개서 목록 (펼쳤을 때) */}
                {isOpen && (
                  <div className="border-t border-gray-100 bg-gray-50/40 px-10 py-3 space-y-2">
                    {company.portfolios.map((p) => (
                      <div
                        key={p.id}
                        className="flex items-center justify-between py-2 px-3 rounded-lg bg-white border border-gray-100 hover:border-gray-200 transition-colors"
                      >
                        <div className="flex items-center gap-3">
                          <VisibleBadge visible={p.visible} />
                          <span className="text-sm text-gray-800 font-medium">{p.title}</span>
                          {p.isAutoGenerated && (
                            <span className="text-[10px] text-gray-400 border border-gray-200 rounded px-1 py-0.5">
                              자동생성
                            </span>
                          )}
                          <span className="text-xs text-gray-400">{p.createdAt}</span>
                        </div>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-7 px-2 text-gray-400 hover:text-gray-700"
                          onClick={() => window.open(`/portfolio`, "_blank")}
                        >
                          <Eye className="h-3.5 w-3.5 mr-1" />
                          보기
                        </Button>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )
          })
        )}
      </div>
    </div>
  )
}
